version: '3'

services:
  NormanCalculator:
    build: ./NormanCalculator
    image: logion/NormanCalculator:v1
    ports: 
      - 5006:80
    networks:
      - front

networks:
  front:
    driver: bridge